### ISSUE TITLE
SSL Error When Connecting to REDIS via Python <upstash-redis>

### ISSUE THREAD

**Issue by shmugoh** [hiett/serverless-redis-http#23]
Attempting to establish a connection to REDIS using the serverless-redis-http server results in an SSL error. The error message received is as follows:
```bash
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=8079): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))
```

Below are the steps to reproduce the error:
```python
from upstash_redis import Redis
r = Redis(url="https://localhost:8079", token="example_token")
r.ping()
```

...and here's the error traceback:
```bash
Traceback (most recent call last):
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\urllib3\util\ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\urllib3\util\ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\ssl.py", line 1046, in _create
    self.do_handshake()
  File "C:\Program Files\Python312\Lib\ssl.py", line 1321, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\urllib3\connectionpool.py", line 492, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=8079): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\upstash_redis\commands.py", line 218, in ping
    return self.execute(command)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\upstash_redis\client.py", line 110, in execute
    res = sync_execute(
          ^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\upstash_redis\http.py", line 141, in sync_execute
    raise last_error
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\upstash_redis\http.py", line 129, in sync_execute
    response = session.post(url, headers=headers, json=command).json()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\code\whereisthegooglecar\bot\env\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=8079): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))
```

**Comment by shmugoh** [comment]
Just realized I accidentally used `https` instead of `http`. Whoops! Closing...
