### ISSUE TITLE
Multi-execs from concurrent users not working

### ISSUE THREAD

**Issue by smartinio** [hiett/serverless-redis-http#25]
The following code snippet works towards actual Upstash but not towards `serverless-redis-http`

### Repro

```ts
import { Redis } from '@upstash/redis'

const redis = Redis.fromEnv()

await Promise.all(['a', 'b', 'c'].map(async (key) => {
  const multi = redis.multi()
  multi.set(key, 'foo')
  await multi.exec()
}))

console.log(await redis.mget('a', 'b', 'c'))
```

### Expected

```ts
[ "foo", "foo", "foo" ]
```

### Observed

```ts
UpstashError: ERR MULTI calls can not be nested, command was: [["set","x","foo","nx","ex",2],["set","y","bar","nx","ex",2]]
      at new u (/Users/sam/redis-http-repro/node_modules/@upstash/redis/chunk-DKKYFKP2.mjs:1:42)
      at /Users/sam/redis-http-repro/node_modules/@upstash/redis/chunk-DKKYFKP2.mjs:1:1597
```

**Comment by hiett** [comment]
Is this output directly from that repro? The command doesn't seem to line up

**Comment by smartinio** [comment]
Sorry, old output from when I tested with options. Updated

**Comment by hiett** [comment]
Investigating now.

**Comment by smartinio** [comment]
Thanks for the quick debug. Will give it a go

**Comment by smartinio** [comment]
That workaround allowed me to complete my integration testing suite and finally deploy my project. Thanks again!

**Comment by hiett** [comment]
All good! I will work on a more concrete solution when I get time, but I'm happy to hear this temporarily solution is working.

Leaving this issue open as a reference point for when I get around to improving the pooling, and for others visibility.

**Comment by Coriou** [comment]
Been using SRH for a while — it's been a great tool and genuinely useful across many of my projects. Because of this issue (and the lack of SSE/PubSub support), I ended up writing a new  version from scratch using the Bun runtime (TypeScript, so same language as the apps that consume it): https://github.com/Coriou/up-redis

Happy to help improve SRH too if that's something you'd still want to do — not trying to promote  anything here, just think SRH is a really useful project (used it in production for years) and wanted to give back in some way.
