### ISSUE TITLE
Issue: Message Not Found

### ISSUE THREAD

**Issue by foochris** [hiett/serverless-redis-http#6]
I'm encountering these errors with this simple script. 

Docker is running both `redis` and `hiett/serverless-redis-http:latest` containers.

Is the issue that url in the client is using `http` instead of `https`?

app.js
```
import { Redis } from "@upstash/redis";

const redisClient = new Redis({
  url: "http://localhost:8080",
  token: "123456789",
});

await redisClient.set('key', 'value');
```

redis (docker)
```
Possible SECURITY ATTACK detected. It looks like somebody is sending POST or Host: commands to Redis. This is likely due to an attacker attempting to use Cross Protocol Scripting to compromise your Redis instance. Connection aborted.
```

node output:
```
(node:13255) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Response.json (node:internal/deps/undici/undici:6160:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpClient.request (file:///node_modules/.pnpm/@upstash+redis@1.20.0/node_modules/@upstash/redis/esm/pkg/http.js:99:23)
    at async SetCommand.exec (file://node_modules/.pnpm/@upstash+redis@1.20.0/node_modules/@upstash/redis/esm/pkg/commands/command.js:55:35)
```

srh log output:
```
16:25:13.857 [error] #PID<0.1106.0> running Srh.Http.BaseRouter (connection #PID<0.1105.0>, stream id 1) terminated
Server: localhost:8080 (http)
Request: POST /
** (exit) an exception was raised:
    ** (KeyError) key :message not found in: %Redix.ConnectionError{reason: :closed}
        (srh 0.1.0) lib/srh/http/command_handler.ex:160: Srh.Http.CommandHandler.dispatch_command/2
        (srh 0.1.0) lib/srh/http/base_router.ex:16: anonymous fn/2 in Srh.Http.BaseRouter.do_match/4
        (srh 0.1.0) lib/plug/router.ex:246: anonymous fn/4 in Srh.Http.BaseRouter.dispatch/2
        (telemetry 1.1.0) /app/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
        (srh 0.1.0) lib/plug/router.ex:242: Srh.Http.BaseRouter.dispatch/2
        (srh 0.1.0) lib/srh/http/base_router.ex:1: Srh.Http.BaseRouter.plug_builder_call/2
        (plug_cowboy 2.5.2) lib/plug/cowboy/handler.ex:12: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
```

**node**
18.12.1

**Docker commands**
```
$ docker run --name my-redis -p 6379:6379 -d redis
$ docker run -it -d -p 8080:80 --name srh --mount type=bind,source=$(pwd)/srh-config/tokens.json,target=/app/srh-config/tokens.json hiett/serverless-redis-http:latest
```

**Comment by hiett** [comment]
Hi, can you show your tokens.json file? It is most likely that it can't connect to the Redis instance

**Comment by foochris** [comment]
@hiett Unfortunately, I won't be needing your project atm.

**Comment by eric-burel** [comment]
Hi @hiett , same issue with no "tokens.json", did I miss something ?
I am running SRH like so:!
```
    docker run \
    --rm \
    -p 8080:80 \
    --label srh \
    -e SRH_MODE=env \
    -e SRH_TOKEN=fake-dev-token \
    -e SRH_CONNECTION_STRING="redis://localhost:6379" \
    hiett/serverless-redis-http:latest
```
The underlying Redis instance is up and running on 6379

**Comment by hiett** [comment]
@eric-burel Hi Eric - the token.json is an alternate approach to definining Redis connections. Its usecase is so you can have multiple redis pools each handled independently. The `SRH_MODE=env` is a new, simpler approach when you just want to target 1 redis server, taking connection details via environment variables rather than a JSON file. The connection is a networking issue that I have replied to in another issue. 
Hope this helps!
Scott
